version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules/
      - /usr/app/.next/
