import { t } from 'i18next'

export const template: any = {
  case_1: {
    id: 1,
    title: 'Template 1 (1 screen)',
    template: '/assets/images/caseroom/template/1.png',
    parts: [
      {
        parts_name: t('caseroom_position_front_smile_image'),
        file_path: '/assets/images/caseroom/front_single.png',
        index_row: 1,
        index_column: 1,
      },
    ],
  },
  case_2: {
    id: 2,
    title: 'Template 2 (8 screens)',
    template: 'https://8screens.jpg',
    parts: [
      {
        index: 0,
        parts_name: t('caseroom_position_side_image'),
        file_path: 'side_face',
        index_row: 1,
        index_column: 1,
        file: null,
        base64: '',
      },
      {
        index: 1,
        parts_name: t('caseroom_position_front_image'),
        file_path: 'front_face',
        index_row: 1,
        index_column: 2,
        file: null,
        base64: '',
      },
      {
        index: 2,
        parts_name: t('caseroom_position_front_smile_image'),
        file_path: 'front_face_with_smile',
        index_row: 1,
        index_column: 3,
        file: null,
        base64: '',
      },
      {
        index: 3,
        parts_name: t('caseroom_position_mouth_up_image'),
        file_path: 'mouth_up',
        index_row: 2,
        index_column: 1,
        file: null,
        base64: '',
      },
      {
        index: 4,
        parts_name: '',
        file_path: '',
        index_row: 0,
        index_column: 0,
      },
      {
        index: 5,
        parts_name: t('caseroom_position_mouth_down_image'),
        file_path: 'mouth_down',
        index_row: 2,
        index_column: 3,
        file: null,
        base64: '',
      },
      {
        index: 6,
        parts_name: t('caseroom_position_mouth_left_image'),
        file_path: 'mouth_left',
        index_row: 3,
        index_column: 1,
        file: null,
        base64: '',
      },
      {
        index: 7,
        parts_name: t('caseroom_position_front_image'),
        file_path: 'mouth_front',
        index_row: 3,
        index_column: 2,
        file: null,
        base64: '',
      },
      {
        index: 8,
        parts_name: t('caseroom_position_mouth_right_image'),
        file_path: 'mouth_right',
        index_row: 3,
        index_column: 3,
        file: null,
        base64: '',
      },
    ],
  },
  case_3: {
    id: 3,
    title: 'Template 3 (5 screens 1)',
    template: 'https://5screens1.jpg',
    parts: [
      {
        index: 0,
        parts_name: '',
        file_path: '',
        index_row: 0,
        index_column: 0,
      },
      {
        index: 1,
        parts_name: t('caseroom_position_mouth_up_image'),
        file_path: 'https://mouth_up.jpg',
        index_row: 1,
        index_column: 2,
        file: null,
        base64: '',
      },
      {
        index: 2,
        parts_name: '',
        file_path: '',
        index_row: 0,
        index_column: 0,
      },
      {
        index: 3,
        parts_name: t('caseroom_position_mouth_left_image'),
        file_path: 'https://left_side_of_the_mouth.jpg',
        index_row: 2,
        index_column: 1,
        file: null,
        base64: '',
      },
      {
        index: 4,
        parts_name: t('caseroom_position_front_image'),
        file_path: 'https://front_of_the_mouth.jpg',
        index_row: 2,
        index_column: 2,
        file: null,
        base64: '',
      },
      {
        index: 5,
        parts_name: t('caseroom_position_mouth_right_image'),
        file_path: 'https://right_side_of_the_mouth.jpg',
        index_row: 2,
        index_column: 3,
        file: null,
        base64: '',
      },
      {
        index: 6,
        parts_name: '',
        file_path: '',
        index_row: 0,
        index_column: 0,
      },
      {
        index: 7,
        parts_name: t('caseroom_position_mouth_down_image'),
        file_path: 'https://mouth_down.jpg',
        index_row: 3,
        index_column: 2,
        file: null,
        base64: '',
      },
      {
        index: 8,
        parts_name: '',
        file_path: '',
        index_row: 0,
        index_column: 0,
      },
    ],
  },
  case_4: {
    id: 4,
    title: 'Template 4 (5 screens 2)',
    template: 'https://5screens2.jpg',
    parts: [
      {
        index: 0,
        parts_name: t('caseroom_position_mouth_up_image'),
        file_path: 'https://mouth_up.jpg',
        index_row: 1,
        index_column: 1,
        file: null,
        base64: '',
      },
      {
        index: 1,
        parts_name: '',
        file_path: '',
        index_row: 0,
        index_column: 0,
      },
      {
        index: 2,
        parts_name: t('caseroom_position_mouth_down_image'),
        file_path: 'https://mouth_down.jpg',
        index_row: 1,
        index_column: 3,
        file: null,
        base64: '',
      },
      {
        index: 3,
        parts_name: t('caseroom_position_mouth_left_image'),
        file_path: 'https://left_side_of_the_mouth.jpg',
        index_row: 2,
        index_column: 1,
        file: null,
        base64: '',
      },
      {
        index: 4,
        parts_name: t('caseroom_position_front_image'),
        file_path: 'https://front_of_the_mouth.jpg',
        index_row: 2,
        index_column: 2,
        file: null,
        base64: '',
      },
      {
        index: 5,
        parts_name: t('caseroom_position_mouth_right_image'),
        file_path: 'https://right_side_of_the_mouth.jpg',
        index_row: 2,
        index_column: 3,
        file: null,
        base64: '',
      },
    ],
  },
  case_5: {
    id: 5,
    title: 'Template 5 (9 screens)',
    template: 'https://9screens.jpg',
    parts: [
      {
        index: 0,
        parts_name: t('caseroom_position_mouth_left_image'),
        file_path: 'https://left_side_of_the_mouth.jpg',
        index_row: 1,
        index_column: 1,
        file: null,
        base64: '',
      },
      {
        index: 1,
        parts_name: t('caseroom_position_front_image'),
        file_path: 'https://front_of_the_mouth.jpg',
        index_row: 1,
        index_column: 2,
        file: null,
        base64: '',
      },
      {
        index: 2,
        parts_name: t('caseroom_position_mouth_right_image'),
        file_path: 'https://right_side_of_the_mouth.jpg',
        index_row: 1,
        index_column: 3,
        file: null,
        base64: '',
      },
      {
        index: 3,
        parts_name: t('caseroom_position_mouth_left_image'),
        file_path: 'https://left_side_of_the_mouth.jpg',
        index_row: 2,
        index_column: 1,
        file: null,
        base64: '',
      },
      {
        index: 4,
        parts_name: t('caseroom_position_front_image'),
        file_path: 'https://front_of_the_mouth.jpg',
        index_row: 2,
        index_column: 2,
        file: null,
        base64: '',
      },
      {
        index: 5,
        parts_name: t('caseroom_position_mouth_right_image'),
        file_path: 'https://right_side_of_the_mouth.jpg',
        index_row: 2,
        index_column: 3,
        file: null,
        base64: '',
      },
      {
        index: 6,
        parts_name: t('caseroom_position_mouth_left_image'),
        file_path: 'https://left_side_of_the_mouth.jpg',
        index_row: 3,
        index_column: 1,
        file: null,
        base64: '',
      },
      {
        index: 7,
        parts_name: t('caseroom_position_front_image'),
        file_path: 'https://front_of_the_mouth.jpg',
        index_row: 3,
        index_column: 2,
        file: null,
        base64: '',
      },
      {
        index: 8,
        parts_name: t('caseroom_position_mouth_right_image'),
        file_path: 'https://right_side_of_the_mouth.jpg',
        index_row: 3,
        index_column: 3,
        file: null,
        base64: '',
      },
    ],
  },
  case_6: {
    id: 6,
    title: 'Template 6 (6 screens 1)',
    template: 'https://6screens1.jpg',
    parts: [
      {
        index: 0,
        parts_name: t('caseroom_position_front_image'),
        file_path: 'https://side_of_the_head.jpg',
        index_row: 1,
        index_column: 1,
        file: null,
        base64: '',
      },
      {
        index: 1,
        parts_name: t('caseroom_position_front_smile_image'),
        file_path: 'https://front_of_the_head.jpg',
        index_row: 1,
        index_column: 2,
        file: null,
        base64: '',
      },
      {
        index: 2,
        parts_name: t('caseroom_position_side_image'),
        file_path: 'https://front_of_the_head_with_smile.jpg',
        index_row: 1,
        index_column: 3,
        file: null,
        base64: '',
      },
      {
        index: 3,
        parts_name: t('caseroom_position_front_image'),
        file_path: 'https://side_of_the_head.jpg',
        index_row: 2,
        index_column: 1,
        file: null,
        base64: '',
      },
      {
        index: 4,
        parts_name: t('caseroom_position_front_smile_image'),
        file_path: 'https://front_of_the_head.jpg',
        index_row: 2,
        index_column: 2,
        file: null,
        base64: '',
      },
      {
        index: 5,
        parts_name: t('caseroom_position_side_image'),
        file_path: 'https://front_of_the_head_with_smile.jpg',
        index_row: 2,
        index_column: 3,
        file: null,
        base64: '',
      },
    ],
  },
  case_7: {
    id: 7,
    title: 'Template 7 (6 screens 2)',
    template: 'https://6screens2.jpg',
    parts: [
      {
        index: 0,
        parts_name: t('caseroom_position_side_image'),
        file_path: 'https://side_of_the_head.jpg',
        index_row: 1,
        index_column: 1,
        file: null,
        base64: '',
      },
      {
        index: 1,
        parts_name: t('caseroom_position_front_image'),
        file_path: 'https://front_of_the_head.jpg',
        index_row: 1,
        index_column: 2,
        file: null,
        base64: '',
      },
      {
        index: 2,
        parts_name: t('caseroom_position_side_image'),
        file_path: 'https://side_face_reverse.png',
        index_row: 1,
        index_column: 3,
        file: null,
        base64: '',
      },
      {
        index: 3,
        parts_name: t('caseroom_position_mouth_left_image'),
        file_path: 'https://left_side_of_the_mouth.jpg',
        index_row: 2,
        index_column: 1,
        file: null,
        base64: '',
      },
      {
        index: 4,
        parts_name: t('caseroom_position_front_image'),
        file_path: 'https://front_of_the_mouth.jpg',
        index_row: 2,
        index_column: 2,
        file: null,
        base64: '',
      },
      {
        index: 5,
        parts_name: t('caseroom_position_mouth_right_image'),
        file_path: 'https://right_side_of_the_mouth.jpg',
        index_row: 2,
        index_column: 3,
        file: null,
        base64: '',
      },
    ],
  },
  case_8: {
    id: 8,
    title: 'Template 8 (6 screens 3)',
    template: 'https://6screens3.jpg',
    parts: [
      {
        index: 0,
        parts_name: t('caseroom_position_mouth_left_image'),
        file_path: 'https://side_of_the_head.jpg',
        index_row: 1,
        index_column: 1,
        file: null,
        base64: '',
      },
      {
        index: 1,
        parts_name: t('caseroom_position_mouth_front_image'),
        file_path: 'https://front_of_the_head.jpg',
        index_row: 1,
        index_column: 2,
        file: null,
        base64: '',
      },
      {
        index: 2,
        parts_name: t('caseroom_position_mouth_right_image'),
        file_path: 'https://front_of_the_head_with_smile.jpg',
        index_row: 1,
        index_column: 3,
        file: null,
        base64: '',
      },
      {
        index: 3,
        parts_name: t('caseroom_position_mouth_left_image'),
        file_path: 'https://left_side_of_the_mouth.jpg',
        index_row: 2,
        index_column: 1,
        file: null,
        base64: '',
      },
      {
        index: 4,
        parts_name: t('caseroom_position_mouth_front_image'),
        file_path: 'https://front_of_the_mouth.jpg',
        index_row: 2,
        index_column: 2,
        file: null,
        base64: '',
      },
      {
        index: 5,
        parts_name: t('caseroom_position_mouth_right_image'),
        file_path: 'https://right_side_of_the_mouth.jpg',
        index_row: 2,
        index_column: 3,
        file: null,
        base64: '',
      },
    ],
  },
  case_9: {
    id: 9,
    title: 'Template 9 (9 screens)',
    template: 'https://9screens.jpg',
    parts: [
      {
        index: 0,
        parts_name: t('caseroom_position_mouth_left_image'),
        file_path: 'https://left_side_of_the_mouth.jpg',
        index_row: 1,
        index_column: 1,
        file: null,
        base64: '',
      },
      {
        index: 1,
        parts_name: t('caseroom_position_front_image'),
        file_path: 'https://front_of_the_mouth.jpg',
        index_row: 1,
        index_column: 2,
        file: null,
        base64: '',
      },
      {
        index: 2,
        parts_name: t('caseroom_position_mouth_right_image'),
        file_path: 'https://right_side_of_the_mouth.jpg',
        index_row: 1,
        index_column: 3,
        file: null,
        base64: '',
      },
      {
        index: 3,
        parts_name: t('caseroom_position_mouth_left_image'),
        file_path: 'https://left_side_of_the_mouth.jpg',
        index_row: 2,
        index_column: 1,
        file: null,
        base64: '',
      },
      {
        index: 4,
        parts_name: t('caseroom_position_front_image'),
        file_path: 'https://front_of_the_mouth.jpg',
        index_row: 2,
        index_column: 2,
        file: null,
        base64: '',
      },
      {
        index: 5,
        parts_name: t('caseroom_position_mouth_right_image'),
        file_path: 'https://right_side_of_the_mouth.jpg',
        index_row: 2,
        index_column: 3,
        file: null,
        base64: '',
      },
      {
        index: 6,
        parts_name: t('caseroom_position_mouth_left_image'),
        file_path: 'https://left_side_of_the_mouth.jpg',
        index_row: 3,
        index_column: 1,
        file: null,
        base64: '',
      },
      {
        index: 7,
        parts_name: t('caseroom_position_front_image'),
        file_path: 'https://front_of_the_mouth.jpg',
        index_row: 3,
        index_column: 2,
        file: null,
        base64: '',
      },
      {
        index: 8,
        parts_name: t('caseroom_position_mouth_right_image'),
        file_path: 'https://right_side_of_the_mouth.jpg',
        index_row: 3,
        index_column: 3,
        file: null,
        base64: '',
      },
    ],
  },
  case_10: {
    id: 10,
    title: 'Template 10 (3 screens)',
    template: '',
    parts: [
      {
        index: 0,
        parts_name: t('caseroom_position_side_image'),
        file_path: '',
        index_row: 1,
        index_column: 1,
        file: null,
        base64: '',
      },
      {
        index: 2,
        parts_name: t('caseroom_position_front_image'),
        file_path: '',
        index_row: 1,
        index_column: 2,
        file: null,
        base64: '',
      },
      {
        index: 3,
        parts_name: t('caseroom_position_mouth_front_image'),
        file_path: '',
        index_row: 1,
        index_column: 2,
        file: null,
        base64: '',
      },
    ],
  },
}
