export const students = [
  {
    id: 1,
    password: 'hashed_password1',
    last_login: '2025-01-20T10:00:00',
    is_superuser: false,
    username: 'student_one',
    first_name: 'Alice',
    last_name: 'Smith',
    email: 'alice.smith@student.example.com',
    is_staff: false,
    is_active: true,
    date_joined: '2025-01-01T08:00:00',
    role: 'student',
    profile_picture: 'profile1.jpg',
    birthdate: '2000-03-22',
    phone_number: '081234567890',
    faculty_id: 101,
    faculty: {
      id: 1,
      name: 'Faculty of Computer Science',
      code: 'FCS',
      description: 'A faculty focused on computer science and IT studies.',
      established_year: 1995,
      dean_name: 'Dr. Alice Johnson',
      contact_email: 'dean.fcs@university.edu',
      contact_phone: '081123456789',
    },
  },
  {
    id: 2,
    password: 'hashed_password2',
    last_login: '2025-01-21T14:00:00',
    is_superuser: false,
    username: 'student_two',
    first_name: 'Bob',
    last_name: 'Brown',
    email: 'bob.brown@student.example.com',
    is_staff: false,
    is_active: true,
    date_joined: '2025-01-05T09:00:00',
    role: 'student',
    profile_picture: 'profile2.jpg',
    birthdate: '2001-07-15',
    phone_number: '081234567891',
    faculty_id: 102,
    faculty: {
      id: 1,
      name: 'Faculty of Computer Science',
      code: 'FCS',
      description: 'A faculty focused on computer science and IT studies.',
      established_year: 1995,
      dean_name: 'Dr. Alice Johnson',
      contact_email: 'dean.fcs@university.edu',
      contact_phone: '081123456789',
    },
  },
  {
    id: 3,
    password: 'hashed_password3',
    last_login: '2025-01-19T16:30:00',
    is_superuser: false,
    username: 'student_three',
    first_name: 'Charlie',
    last_name: 'Davis',
    email: 'charlie.davis@student.example.com',
    is_staff: false,
    is_active: true,
    date_joined: '2025-01-07T10:00:00',
    role: 'student',
    profile_picture: 'profile3.jpg',
    birthdate: '1999-12-10',
    phone_number: '081234567892',
    faculty_id: 103,
    faculty: {
      id: 1,
      name: 'Faculty of Computer Science',
      code: 'FCS',
      description: 'A faculty focused on computer science and IT studies.',
      established_year: 1995,
      dean_name: 'Dr. Alice Johnson',
      contact_email: 'dean.fcs@university.edu',
      contact_phone: '081123456789',
    },
  },
  {
    id: 4,
    password: 'hashed_password4',
    last_login: '2025-01-18T09:15:00',
    is_superuser: false,
    username: 'student_four',
    first_name: 'Diana',
    last_name: 'Evans',
    email: 'diana.evans@student.example.com',
    is_staff: false,
    is_active: true,
    date_joined: '2025-01-10T09:20:00',
    role: 'student',
    profile_picture: 'profile4.jpg',
    birthdate: '2002-03-05',
    phone_number: '081234567893',
    faculty_id: 104,
    faculty: {
      id: 1,
      name: 'Faculty of Computer Science',
      code: 'FCS',
      description: 'A faculty focused on computer science and IT studies.',
      established_year: 1995,
      dean_name: 'Dr. Alice Johnson',
      contact_email: 'dean.fcs@university.edu',
      contact_phone: '081123456789',
    },
  },
  {
    id: 5,
    password: 'hashed_password5',
    last_login: '2025-01-17T12:45:00',
    is_superuser: false,
    username: 'student_five',
    first_name: 'Eve',
    last_name: 'Green',
    email: 'eve.green@student.example.com',
    is_staff: false,
    is_active: true,
    date_joined: '2025-01-11T12:00:00',
    role: 'student',
    profile_picture: 'profile5.jpg',
    birthdate: '2003-05-10',
    phone_number: '081234567894',
    faculty_id: 105,
    faculty: {
      id: 1,
      name: 'Faculty of Computer Science',
      code: 'FCS',
      description: 'A faculty focused on computer science and IT studies.',
      established_year: 1995,
      dean_name: 'Dr. Alice Johnson',
      contact_email: 'dean.fcs@university.edu',
      contact_phone: '081123456789',
    },
  },
  {
    id: 6,
    password: 'hashed_password6',
    last_login: '2025-01-22T11:20:00',
    is_superuser: false,
    username: 'student_six',
    first_name: 'Frank',
    last_name: 'Harris',
    email: 'frank.harris@student.example.com',
    is_staff: false,
    is_active: true,
    date_joined: '2025-01-12T08:30:00',
    role: 'student',
    profile_picture: 'profile6.jpg',
    birthdate: '2000-06-25',
    phone_number: '081234567895',
    faculty_id: 106,
    faculty: {
      id: 1,
      name: 'Faculty of Computer Science',
      code: 'FCS',
      description: 'A faculty focused on computer science and IT studies.',
      established_year: 1995,
      dean_name: 'Dr. Alice Johnson',
      contact_email: 'dean.fcs@university.edu',
      contact_phone: '081123456789',
    },
  },
  {
    id: 7,
    password: 'hashed_password7',
    last_login: '2025-01-23T18:00:00',
    is_superuser: false,
    username: 'student_seven',
    first_name: 'Grace',
    last_name: 'James',
    email: 'grace.james@student.example.com',
    is_staff: false,
    is_active: true,
    date_joined: '2025-01-13T14:30:00',
    role: 'student',
    profile_picture: 'profile7.jpg',
    birthdate: '2001-01-15',
    phone_number: '081234567896',
    faculty_id: 107,
    faculty: {
      id: 1,
      name: 'Faculty of Computer Science',
      code: 'FCS',
      description: 'A faculty focused on computer science and IT studies.',
      established_year: 1995,
      dean_name: 'Dr. Alice Johnson',
      contact_email: 'dean.fcs@university.edu',
      contact_phone: '081123456789',
    },
  },
  {
    id: 8,
    password: 'hashed_password8',
    last_login: '2025-01-20T08:40:00',
    is_superuser: false,
    username: 'student_eight',
    first_name: 'Hank',
    last_name: 'Miller',
    email: 'hank.miller@student.example.com',
    is_staff: false,
    is_active: true,
    date_joined: '2025-01-14T09:00:00',
    role: 'student',
    profile_picture: 'profile8.jpg',
    birthdate: '2002-09-10',
    phone_number: '081234567897',
    faculty_id: 108,
    faculty: {
      id: 1,
      name: 'Faculty of Computer Science',
      code: 'FCS',
      description: 'A faculty focused on computer science and IT studies.',
      established_year: 1995,
      dean_name: 'Dr. Alice Johnson',
      contact_email: 'dean.fcs@university.edu',
      contact_phone: '081123456789',
    },
  },
  {
    id: 9,
    password: 'hashed_password9',
    last_login: '2025-01-24T20:00:00',
    is_superuser: false,
    username: 'student_nine',
    first_name: 'Ivy',
    last_name: 'Nelson',
    email: 'ivy.nelson@student.example.com',
    is_staff: false,
    is_active: true,
    date_joined: '2025-01-15T10:15:00',
    role: 'student',
    profile_picture: 'profile9.jpg',
    birthdate: '2003-04-18',
    phone_number: '081234567898',
    faculty_id: 109,
    faculty: {
      id: 1,
      name: 'Faculty of Computer Science',
      code: 'FCS',
      description: 'A faculty focused on computer science and IT studies.',
      established_year: 1995,
      dean_name: 'Dr. Alice Johnson',
      contact_email: 'dean.fcs@university.edu',
      contact_phone: '081123456789',
    },
  },
  {
    id: 10,
    password: 'hashed_password10',
    last_login: '2025-01-25T10:10:00',
    is_superuser: false,
    username: 'student_ten',
    first_name: 'Jack',
    last_name: 'Owen',
    email: 'jack.owen@student.example.com',
    is_staff: false,
    is_active: true,
    date_joined: '2025-01-16T09:20:00',
    role: 'student',
    profile_picture: 'profile10.jpg',
    birthdate: '2002-11-25',
    phone_number: '081234567899',
    faculty_id: 110,
    faculty: {
      id: 1,
      name: 'Faculty of Computer Science',
      code: 'FCS',
      description: 'A faculty focused on computer science and IT studies.',
      established_year: 1995,
      dean_name: 'Dr. Alice Johnson',
      contact_email: 'dean.fcs@university.edu',
      contact_phone: '081123456789',
    },
  },
]

export const faculties = [
  {
    id: 1,
    name: 'Faculty of Computer Science',
    code: 'FCS',
    description: 'A faculty focused on computer science and IT studies.',
    established_year: 1995,
    dean_name: 'Dr. Alice Johnson',
    contact_email: 'dean.fcs@university.edu',
    contact_phone: '081123456789',
  },
  {
    id: 2,
    name: 'Faculty of Mathematics',
    code: 'FMATH',
    description: 'A faculty dedicated to advanced mathematics and statistics.',
    established_year: 1980,
    dean_name: 'Dr. Bob Smith',
    contact_email: 'dean.fmath@university.edu',
    contact_phone: '081123456790',
  },
  {
    id: 3,
    name: 'Faculty of Physics',
    code: 'FPHYS',
    description: 'A faculty offering theoretical and applied physics programs.',
    established_year: 1975,
    dean_name: 'Dr. Charlie Brown',
    contact_email: 'dean.fphys@university.edu',
    contact_phone: '081123456791',
  },
]

export const lecturer = [
  {
    id: 101,
    password: 'hashed_password1',
    last_login: '2025-01-20T10:00:00',
    is_superuser: true,
    username: 'lecturer_one',
    first_name: 'John',
    last_name: 'Doe',
    email: 'john.doe@example.com',
    is_staff: true,
    is_active: true,
    date_joined: '2023-01-15T12:30:00',
    role: 'lecturer',
    profile_picture: 'lecturer1.jpg',
    birthdate: '1980-05-20',
    phone_number: '081123456789',
    faculity: faculties[0],
  },
  {
    id: 102,
    password: 'hashed_password2',
    last_login: '2025-01-21T14:00:00',
    is_superuser: false,
    username: 'lecturer_two',
    first_name: 'Jane',
    last_name: 'Smith',
    email: 'jane.smith@example.com',
    is_staff: true,
    is_active: true,
    date_joined: '2024-02-10T11:00:00',
    role: 'lecturer',
    profile_picture: 'lecturer2.jpg',
    birthdate: '1985-08-15',
    phone_number: '081123456790',
    faculity: faculties[0],
  },
]

export const studyPrograms = [
  {
    id: 1,
    name: 'Computer Science',
    code: 'CS',
    description: 'A program focused on computer science fundamentals.',
    head_of_program: 'Dr. Alice Johnson',
    established_year: 2000,
    contact_email: 'cs@university.edu',
    contact_phone: '081123456789',
    faculty: {
      id: 1,
      name: 'Faculty of Computer Science',
      code: 'FCS',
      description: 'A faculty focused on computer science and IT studies.',
      established_year: 1995,
      dean_name: 'Dr. Alice Johnson',
      contact_email: 'dean.fcs@university.edu',
      contact_phone: '081123456789',
    },
  },
  {
    id: 2,
    name: 'Mathematics',
    code: 'MATH',
    description: 'A program dedicated to advanced mathematics.',
    head_of_program: 'Dr. Bob Smith',
    established_year: 1998,
    contact_email: 'math@university.edu',
    contact_phone: '081123456790',
    faculty: {
      id: 2,
      name: 'Faculty of Mathematics',
      code: 'FMATH',
      description:
        'A faculty dedicated to advanced mathematics and statistics.',
      established_year: 1980,
      dean_name: 'Dr. Bob Smith',
      contact_email: 'dean.fmath@university.edu',
      contact_phone: '081123456790',
    },
  },
  {
    id: 3,
    name: 'Physics',
    code: 'PHYS',
    description: 'A program for applied and theoretical physics.',
    head_of_program: 'Dr. Charlie Brown',
    established_year: 2005,
    contact_email: 'physics@university.edu',
    contact_phone: '081123456791',
    faculty: {
      id: 3,
      name: 'Faculty of Physics',
      code: 'FPHYS',
      description:
        'A faculty offering theoretical and applied physics programs.',
      established_year: 1975,
      dean_name: 'Dr. Charlie Brown',
      contact_email: 'dean.fphys@university.edu',
      contact_phone: '081123456791',
    },
  },
  {
    id: 4,
    name: 'Information Systems',
    code: 'IS',
    description:
      'A program focusing on information systems and their applications.',
    head_of_program: 'Dr. Emily Davis',
    established_year: 2003,
    contact_email: 'is@university.edu',
    contact_phone: '081123456792',
    faculty: {
      id: 1,
      name: 'Faculty of Computer Science',
      code: 'FCS',
      description: 'A faculty focused on computer science and IT studies.',
      established_year: 1995,
      dean_name: 'Dr. Alice Johnson',
      contact_email: 'dean.fcs@university.edu',
      contact_phone: '081123456789',
    },
  },
  {
    id: 5,
    name: 'Applied Statistics',
    code: 'STAT',
    description: 'A program focused on applied statistics and data analysis.',
    head_of_program: 'Dr. Mark White',
    established_year: 2010,
    contact_email: 'stat@university.edu',
    contact_phone: '081123456793',
    faculty: {
      id: 2,
      name: 'Faculty of Mathematics',
      code: 'FMATH',
      description:
        'A faculty dedicated to advanced mathematics and statistics.',
      established_year: 1980,
      dean_name: 'Dr. Bob Smith',
      contact_email: 'dean.fmath@university.edu',
      contact_phone: '081123456790',
    },
  },
  {
    id: 6,
    name: 'Astrophysics',
    code: 'ASTRO',
    description: 'A program for students specializing in astrophysics.',
    head_of_program: 'Dr. Nina Black',
    established_year: 2015,
    contact_email: 'astro@university.edu',
    contact_phone: '081123456794',
    faculty: {
      id: 3,
      name: 'Faculty of Physics',
      code: 'FPHYS',
      description:
        'A faculty offering theoretical and applied physics programs.',
      established_year: 1975,
      dean_name: 'Dr. Charlie Brown',
      contact_email: 'dean.fphys@university.edu',
      contact_phone: '081123456791',
    },
  },
]

export const classes = [
  [
    {
      id: '227d52e4-4b23-4301-b0e7-f24424dc4ab3',
      name: 'Deep Learning',
      code: '1233',
      description: '-',
      class_availability: 40,
      thumbnail: '-',
      tag: 'ML',
      lecturer: {
        id: 2,
        username: 'Dewi Arianti Wulandari',
        email: 'dewi.wulandari@itpln.ac.id',
        role: 'Dosen',
        faculty: {
          id: '549b1db3-9b14-4191-8271-eda8b12ceda9',
          name: 'Telematika Energi',
          code: 'ften',
          description: '-',
          estalbished: '2023-07-04',
          dean_name: 'Andi',
          email: 'ften@itpln.ac.id',
          phone: '081234567',
        },
        study_program: {
          id: 'ff439879-1277-460b-8f32-bf733a54adcf',
          name: 'Sistem Informasi',
          code: '51',
          description: 'test',
          estalbished: '2025-01-05',
          head_name: 'Budi',
          email: 'si@itpln.ac.id',
          phone: '081234567',
          faculty_id: '549b1db3-9b14-4191-8271-eda8b12ceda9',
        },
      },
      study_program: {
        id: 'ff439879-1277-460b-8f32-bf733a54adcf',
        name: 'Sistem Informasi',
        code: '51',
        description: 'test',
        estalbished: '2025-01-05',
        head_name: 'Budi',
        email: 'si@itpln.ac.id',
        phone: '081234567',
        faculty_id: '549b1db3-9b14-4191-8271-eda8b12ceda9',
      },
      periodId: 'e327e2e0-eac4-413d-9c15-38d4582d875f',
      created_at: '2025-01-30T21:13:44.777392Z',
      updated_at: '2025-01-30T21:13:44.777392Z',
    },
    {
      id: 'b6972df8-3a01-447c-87ca-371650a7a766',
      name: 'Pemograman Object',
      code: '1234',
      description: 'test',
      class_availability: 40,
      thumbnail: '-',
      tag: 'PBO, OOP',
      lecturer: {
        id: 2,
        username: 'Dewi Arianti Wulandari',
        email: 'dewi.wulandari@itpln.ac.id',
        role: 'Dosen',
        faculty: {
          id: '549b1db3-9b14-4191-8271-eda8b12ceda9',
          name: 'Telematika Energi',
          code: 'ften',
          description: '-',
          estalbished: '2023-07-04',
          dean_name: 'Andi',
          email: 'ften@itpln.ac.id',
          phone: '081234567',
        },
        study_program: {
          id: 'ff439879-1277-460b-8f32-bf733a54adcf',
          name: 'Sistem Informasi',
          code: '51',
          description: 'test',
          estalbished: '2025-01-05',
          head_name: 'Budi',
          email: 'si@itpln.ac.id',
          phone: '081234567',
          faculty_id: '549b1db3-9b14-4191-8271-eda8b12ceda9',
        },
      },
      study_program: {
        id: 'ff439879-1277-460b-8f32-bf733a54adcf',
        name: 'Sistem Informasi',
        code: '51',
        description: 'test',
        estalbished: '2025-01-05',
        head_name: 'Budi',
        email: 'si@itpln.ac.id',
        phone: '081234567',
        faculty_id: '549b1db3-9b14-4191-8271-eda8b12ceda9',
      },
      periodId: 'e327e2e0-eac4-413d-9c15-38d4582d875f',
      created_at: '2025-01-26T11:33:15.380937Z',
      updated_at: '2025-01-30T21:15:55.350161Z',
    },
    {
      id: '16801384-f963-4d8d-b67a-26613a3058b7',
      name: 'test',
      code: '1231',
      description: '-',
      class_availability: 40,
      thumbnail: '-',
      tag: 'test',
      lecturer: {
        id: 1,
        username: '',
        email: 'admin@skuring.com',
        role: 'Admin Prodi',
        faculty: null,
        study_program: null,
      },
      study_program: {
        id: 'ff439879-1277-460b-8f32-bf733a54adcf',
        name: 'Sistem Informasi',
        code: '51',
        description: 'test',
        estalbished: '2025-01-05',
        head_name: 'Budi',
        email: 'si@itpln.ac.id',
        phone: '081234567',
        faculty_id: '549b1db3-9b14-4191-8271-eda8b12ceda9',
      },
      periodId: 'e327e2e0-eac4-413d-9c15-38d4582d875f',
      created_at: '2025-01-29T22:52:53.886415Z',
      updated_at: '2025-01-29T22:52:53.886415Z',
    },
  ],
]
